import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import api from "../api.js";

const TOOL_LABEL = {
  get_risk_assessment: "Assessed ward risk",
  get_rainfall_outlook: "Checked rainfall",
  search_sops: "Searched SOPs",
  get_resource_inventory: "Checked resources",
};

// Collapse repeated tool calls into "Searched SOPs ×4" chips.
function toolChips(tools) {
  const counts = {};
  tools.forEach((t) => (counts[t] = (counts[t] || 0) + 1));
  return Object.entries(counts).map(([t, n]) => ({
    label: TOOL_LABEL[t] || t, n,
  }));
}

export default function ResponsePlan({ focus }) {
  const [status, setStatus] = useState(null);
  const [busy, setBusy] = useState(false);
  const [res, setRes] = useState(null);
  const [err, setErr] = useState(null);

  useEffect(() => {
    api.agentStatus().then(setStatus).catch(() => {});
  }, []);

  async function generate() {
    if (busy) return;
    setBusy(true); setErr(null); setRes(null);
    try {
      setRes(await api.responsePlan(focus));
    } catch (e) {
      setErr(String(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col h-full">
      <div className="px-4 pt-3 pb-3 border-b border-ink-600">
        <div className="text-sm font-semibold">
          <span className="text-accent">Response Planner</span>
          <span className="text-[11px] text-slate-500 font-normal ml-2">
            ADK agent · grounded in NDMA SOPs
          </span>
        </div>
        <button
          onClick={generate}
          disabled={busy}
          className="mt-2 w-full py-2 rounded bg-accent text-ink-900 text-sm font-semibold
                     disabled:opacity-50 hover:brightness-110 transition"
        >
          {busy ? "Agent is reasoning…" : "⚡ Generate Response Plan"}
        </button>
        {status?.sop_sources?.length > 0 && (
          <div className="mt-2 text-[10px] text-slate-500">
            Cites: {status.sop_sources.join(" · ")}
          </div>
        )}
      </div>

      <div className="flex-1 overflow-auto p-4">
        {busy && (
          <div className="space-y-2 text-sm text-slate-400">
            <div className="animate-pulse">The agent is calling its tools…</div>
            <ul className="text-[12px] text-slate-500 list-disc ml-4">
              <li>reading ward risk scores</li>
              <li>searching NDMA/urban-flood SOPs</li>
              <li>allocating (simulated) resources</li>
              <li>drafting the plan + citizen advisory</li>
            </ul>
          </div>
        )}
        {err && <div className="text-sm text-risk-high">Error: {err}</div>}
        {res && !res.ok && (
          <div className="text-sm text-amber-400">{res.error}</div>
        )}
        {res && res.ok && (
          <div className="space-y-3">
            <div className="flex flex-wrap gap-1.5">
              {toolChips(res.tools_used).map((c, i) => (
                <span key={i} className="text-[11px] px-2 py-0.5 rounded-full
                                 bg-ink-700 text-accent border border-ink-600">
                  {c.label}{c.n > 1 ? ` ×${c.n}` : ""}
                </span>
              ))}
            </div>

            <div className="prose-plan text-sm leading-relaxed">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{res.text}</ReactMarkdown>
            </div>

            {res.sop_citations?.length > 0 && (
              <div className="pt-2 border-t border-ink-600">
                <div className="text-[11px] uppercase tracking-wide text-slate-500 mb-1">
                  Sources cited
                </div>
                <ul className="space-y-1">
                  {res.sop_citations.map((c, i) => (
                    <li key={i} className="text-[12px] text-slate-300">
                      📄 {c.cite} — p.{c.page}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            <div className="text-[10px] text-slate-600">
              Generated by ADK agent ({res.model}). Resource inventory is simulated.
            </div>
          </div>
        )}
        {!res && !busy && !err && (
          <div className="text-sm text-slate-500">
            Click <b className="text-slate-300">Generate Response Plan</b>. An ADK agent
            reads live risk, searches official flood-management SOPs, allocates
            resources, and drafts a prioritized action plan where every action cites
            the SOP that justifies it — plus a citizen advisory.
          </div>
        )}
      </div>
    </div>
  );
}
